# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:

    runs-on: windows-latest
    
    env:
      CONFIGURATION: "Release"
          
    steps:
    # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Setup msbuild
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    # Run msbuild
    - name: Build project
      working-directory: UnitTesting-Tests
      if: success()
      run: msbuild UnitTesting-Tests.sqlproj
            
    # Create artifact staging directory
    - name: Create artifact staging directory
      if: success()
      run: 'mkdir "staging"'
    
    # Create artifact staging directory
    - name: Create artifact staging directory
      if: success()
      run: 'copy "UnitTesting-Tests\\bin\\release\*.*" "staging"'
    
    # Upload the artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: Database
        # A file, directory or wildcard pattern that describes what to upload
        path: staging\*.*
        
  test:
    
    runs-on: ubuntu-latest
    
    steps:
      
      # Create artifact staging directory
      - name: Create artifact staging directory
        run: 'mkdir "artifact"'
      
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          # Artifact name
          name: Database
          # Destination path
          #path: artifact
          
      - name: Check contents
        run: "ls -la"
    
