# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CONFIGURATION: release
  SQLINSTANCE: localhost
  DATABASE: UnitTesting
  ARTIFACTNAME: Database

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    # Setup msbuild
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    
    # Run msbuild
    - name: Build project
      working-directory: ${{DATABASE}}-Tests
      run: msbuild ${{DATABASE}}-Tests.sqlproj
    
    # Create artifact staging directory
    - name: Create artifact staging directory
      run: 'mkdir "$GITHUB_WORKSPACE\staging"'
    
    # Create artifact staging directory
    - name: Create artifact staging directory
      run: 'copy ${{DATABASE}}-Tests\bin\${{CONFIGURATION}}\*.* "$GITHUB_WORKSPACE\\staging"'
    
    # Upload the artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: ${{ARTIFACTNAME}}
        # A file, directory or wildcard pattern that describes what to upload
        path: $GITHUB_WORKSPACE\staging\*.*
